In [26]:
#Challenge
import numpy as np

sales = np.array([
    1200, 900, 1800, 1500,
    2200, 800, 1700, 1100,
    1900, 2100, 1300, 1600
])

print("Original Array:",sales)
print("Array Shape:",sales.shape)

reshape = sales.reshape(3, 4)

print(reshape)
print("Reshape Size", reshape.shape)
print("Highest: ", np.max(sales))
print("Lowest: ", np.min(sales))
print("Assending order: ", np.sort(sales))
print("Decending order: ", np.sort(sales)[::-1])
print("Average: ", np.average(sales))
print("Top 3: ", np.sort(sales)[-3:])
print("Least 3: ", np.sort(sales)[:3])

Original Array: [1200  900 1800 1500 2200  800 1700 1100 1900 2100 1300 1600]
Array Shape: (12,)
[[1200  900 1800 1500]
 [2200  800 1700 1100]
 [1900 2100 1300 1600]]
Reshape Size (3, 4)
Highest:  2200
Lowest:  800
Assending order:  [ 800  900 1100 1200 1300 1500 1600 1700 1800 1900 2100 2200]
Decending order:  [2200 2100 1900 1800 1700 1600 1500 1300 1200 1100  900  800]
Average:  1508.3333333333333
Top 3:  [1900 2100 2200]
Least 3:  [ 800  900 1100]
