In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr[0])
print(arr[1:4])

[10 20 30 40 50]
10
[20 30 40]


In [2]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.sqrt(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[3.16227766 4.47213595 5.47722558 6.32455532]
25.0
40
10
100


In [9]:
import numpy as np

marks = np.array([85,72,91,67,88,95,78,69,82,90])

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Total:", np.sum(marks))

print("Students above 80:")
print(marks[marks>80])

print("No.of Students passed: ", np.count_nonzero(marks[marks>35]))
print("No.of Students above 90: ", np.count_nonzero(marks[marks>90]))
print("Average percentage: ", (np.mean(marks)/100)*100,"%")

Average: 81.7
Highest: 95
Lowest: 67
Total: 817
Students above 80:
[85 91 88 95 82 90]
No.of Students passed:  10
No.of Students above 90:  2
Average percentage:  81.7 %
