In [5]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

marks = np.array([50, 60, 70])

print(marks + 5)
print(marks * 2)

marks = np.array([25, 40, 55, 70, 85])

print(marks > 50)
print(marks[marks > 50])

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[55 65 75]
[100 120 140]
[False False  True  True  True]
[55 70 85]


In [8]:
marks = np.array([25, 40, 55, 70, 85])

print(marks[(marks > 40) & (marks < 80)])

print(np.random.randint(1, 100, 10))

[55 70]
[79  9  4  9 47 36 95 13 21 80]


In [19]:
arr = np.arange(1, 25)

print(arr.reshape(4, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
arr1 = np.arange(0, 21)

print(arr1[arr1 % 2 == 0])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [17]:
print(np.random.randint(1, 100, 15))

[16 82 88 38 93 72 45 57 73 14 87 70 87 54 26]


In [24]:
marks = np.array([45, 67, 82, 90, 33, 76, 58])

print(marks[marks>60])
print(marks[marks<35])
print(np.count_nonzero(marks>75))
print(len(marks[marks > 75]))

[67 82 90 76]
[33]
3
3


In [29]:
sales = np.array([1200, 1500, 1800, 900, 2000, 1750, 800])

print("Total Weekly Sale: ")
print(np.sum(sales))
print("Average daily sale:")
print(np.mean(sales))
print("Highest and Lowest Sales:")
print(np.max(sales),"&", np.min(sales))
print("Days where sales exceeded 1500")
print(sales[sales > 1500])

Total Weekly Sale: 
9950
Average daily sale:
1421.4285714285713
Highest and Lowest Sales:
2000 & 800
Days where sales exceeded 1500
[1800 2000 1750]
